[package]
name = "rust_cache"
version = "0.1.0"
authors = ["Yosef Deray <yosefderay770@gmail.com>"]

[dependencies]
time = "0.1"

rust-crypto = { version = "0.2.34", optional = true }

[features]
default = ["hash_map"]
hash_map = []
filesystem = ["rust-crypto"]